version: '3.3'

services:
  db: 
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./sqldump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: starwarsapi
      MYSQL_USER: user
      MYSQL_PASSWORD: password



