version: '3.3'

services:
  db: 
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: starwarsapi
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  mysql_data:
